version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework:spring-orm
    versions:
    - 5.3.2
  - dependency-name: org.springframework:spring-context-support
    versions:
    - 5.3.2
  - dependency-name: org.springframework:spring-tx
    versions:
    - 5.3.2
  - dependency-name: org.springframework:spring-expression
    versions:
    - 5.3.2
  - dependency-name: org.springframework:spring-context
    versions:
    - 5.3.2
  - dependency-name: org.springframework:spring-core
    versions:
    - 5.3.2
  - dependency-name: org.springframework:spring-beans
    versions:
    - 5.3.2
  - dependency-name: org.springframework:spring-test
    versions:
    - 5.3.2
  - dependency-name: com.thoughtworks.xstream:xstream
    versions:
    - 1.4.15
  - dependency-name: com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider
    versions:
    - 2.12.0
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.0
  - dependency-name: com.fasterxml.jackson.core:jackson-annotations
    versions:
    - 2.12.0
  - dependency-name: com.fasterxml.jackson.core:jackson-core
    versions:
    - 2.12.0
  - dependency-name: org.springframework.security:spring-security-core
    versions:
    - 5.4.1
  - dependency-name: org.springframework.security:spring-security-config
    versions:
    - 5.4.1
